version: '3'
services:
  web:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile.dev
    command: bash -c "cd api && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - rails-bundle:/app/api/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpack
    stdin_open: true
    tty: true
  webpack:
    build:
      context: ./front
      dockerfile: ../docker/front/Dockerfile.dev
    command: sh -c "cd front && yarn start"
    volumes:
      - .:/app
      - node_modules:/front/node_modules
    ports:
      - "8000:3000"
    tty: true
  db:
    image: mysql:8.0.22
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "4306:3306"
volumes:
  mysql-data:
  rails-bundle:
  node_modules:
